[project]
name = "langchain-searchagent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "black>=26.10.0",
    "deepagents>=0.7.22",
    "isort>=9.0.2",
    "langchain>=1.4.3",
    "langchain-google-genai>=4.4.0",
    "langchain-openai>=1.6.7",
    "langchain-tavily>=0.2.18",
    "python-dotenv>=1.2.4",
    "tavily-python>=0.8.5",
]

[dependency-groups]
dev = [
    "debugpy>=1.8.22",
]
